SCEC/src/com/salary/model/SalaryDAO.java
package com.salary.model;

import java.util.*;
import java.sql.*;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import com.util.SCECcommon;

public class SalaryDAO implements SalaryDAO_interface {
	private static DataSource ds = null;
	
	static {
		try {
			Context ctx = new InitialContext();
			ds = (DataSource) ctx.lookup(SCECcommon.ctxStr);
		} catch (NamingException e) {
			e.printStackTrace();
		}
	}

	private static final String INSERT_STMT = 
			"INSERT INTO SALARY (title_id, salary_level, salary) " +
			"VALUES (?, ?, ?)";
	private static final String GET_ALL_STMT = 
		"SELECT salary_id, title_id, salary_level, salary FROM SALARY order by salary";
	private static final String GET_ONE_STMT = 
		"SELECT * FROM SALARY where title_id = ? AND salary_level = ?";
	private static final String DELETE = 
		"DELETE FROM TITLE where title_id = ?";
	private static final String UPDATE = 
		"UPDATE TITLE set series_id = ?, level_id = ? where title_id = ? and salary_level = ?";
	private static final String SETUP = 
		"UPDATE TITLE set series_id = ? , level_id = ? where title_id = ? and salary_level = ?";
	private static final String FIND_BY_TITLE = 
		"SELECT title_id, name, series_id, level_id FROM TITLE where name = ?";

	@Override
	public void insert(SalaryVO salaryVO) {
		Connection con = null;
		PreparedStatement pstmt = null;

		try {
			con = ds.getConnection();
			pstmt = con.prepareStatement(INSERT_STMT);

			pstmt.setInt(1, salaryVO.getTitleId());
			pstmt.setInt(2, salaryVO.getSalaryLevel());
			pstmt.setInt(3, salaryVO.getSalary());
		
			pstmt.executeUpdate();

			// Handle any driver errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}

	}
	

	@Override
	public SalaryVO findByPrimaryKey(Integer titleId, Integer salaryLevel) {

		SalaryVO salaryVO = null;
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {
			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_ONE_STMT);

			pstmt.setInt(1, titleId);
			pstmt.setInt(2, salaryLevel);
	
			rs = pstmt.executeQuery();

			while (rs.next()) {
				salaryVO = new SalaryVO();
				salaryVO.setSalaryId(rs.getInt("salary_id"));
				salaryVO.setTitleId(rs.getInt("title_id"));
				salaryVO.setSalaryLevel(rs.getInt("salary_level"));
				salaryVO.setSalary(rs.getInt("salary"));
			}
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return salaryVO;
	}

	@Override
	public List<SalaryVO> getAll() {
		List<SalaryVO> list = new ArrayList<SalaryVO>();
		SalaryVO salaryVO = null;

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_ALL_STMT);
			rs = pstmt.executeQuery();

			while (rs.next()) {
				salaryVO = new SalaryVO();
				salaryVO.setSalaryId(rs.getInt("salary_id"));
				salaryVO.setTitleId(rs.getInt("title_id"));
				salaryVO.setSalaryLevel(rs.getInt("salary_level"));
				salaryVO.setSalary(rs.getInt("salary"));
				list.add(salaryVO);
			}

			// Handle any driver errors
		}catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return list;
	}
	

}

SCEC/WebContent/dept/listAllDept.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.*"%>
<%@ page import="com.department.model.*"%>

<%  
// EmpService empSvc = new EmpService();
// List<EmpVO> list = empSvc.getAll();
// pageContext.setAttribute("list",list);
int deptId = 0;
Boolean included = (Boolean)request.getAttribute("included");
HashMap<Integer, Integer> deptMap = DepartmentService.numOfEmpDept;
HashMap <String, String> deptMap2 = new HashMap<String, String>();
deptMap2.put("1", "a");
deptMap2.put("2", "b");
deptMap2.put("3", "c");
request.setAttribute("deptMap", deptMap);
request.setAttribute("deptMap2", deptMap2);
%>
<jsp:useBean id="deptSvc" scope="page" class="com.department.model.DepartmentService" />

<html>
<head>
<title>┮Τ场 </title>
<link rel="stylesheet" href="<%=request.getContextPath()%>/util/jquery/tablesorter/style.css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/util/css/style.css" />
<!--
<link rel="stylesheet" href="<%=request.getContextPath()%>/util/css/common.css" />
-->

<script src="<%=request.getContextPath()%>/util/jquery/jquery-1.9.1.js"> </script>
<script src="<%=request.getContextPath()%>/util/jquery/tablesorter/jquery.tablesorter.js"> </script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script src="<%=request.getContextPath()%>/util/chart/google_chart.js"> </script>

<!-- Bootstrap -->
<% 
//Cannot include bootstrap.css twice
Boolean hasBootstrap = (Boolean)request.getAttribute("hasBootstrap");
	if (hasBootstrap == null) {
%>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/util/bootstrap2.3.2/css/bootstrap.css" />
		<style type="text/css">
			body {
			/*
				padding-top: 60px;
				padding-bottom: 40px;
				*/
			}
		</style>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/util/bootstrap2.3.2/css/bootstrap-responsive.css" />
		<link rel="stylesheet" href="<%=request.getContextPath()%>/util/bootstrap2.3.2/css/logo-nav.css" />
		<script src="<%=request.getContextPath()%>/util/bootstrap2.3.2/js/bootstrap.js"> </script>
<%
		hasBootstrap = true;
		request.setAttribute("hasBootstrap", hasBootstrap);
	} //end of if
%>
<script type="text/javascript">
	$(function () {
    	$("#deptTable").tablesorter({widgets: ['zebra']});
		$(".showDetail").fancybox();
	});
</script>

</head>

<body>

<div class="wrapper">
	<div class="header">
		<% if (included == null) { %>
			<%@include file="../menu.jsp"%>
		<% 
			included = true;
			request.setAttribute("included", included);	
		}
		%>
	</div>
	<div class="container">
		<div class="push"></div>
		<div class="row">
			<div class="span20">
				<ul class="breadcrumb">
					<li><a href="#">琩高</a> <span class="divider">&gt;</span></li>
					<li class="active">场舱麓</li>
				</ul>
			</div>
		</div>
		
		<table id="deptTable" class="tablesorter">
			<thead>
			<tr>
				<th><h4>场絪腹</h4></th>
				<th><h4>场嘿</h4></th>
				<th><h4>场计</h4></th>
				<!--
				<th>э</th>
				<th>埃<font color=red>(闽羛代刚籔ユ-み)</font></th>
				-->
			</tr>
			</thead>
			
			<c:forEach var="deptVO" items="${deptSvc.all}">
				<tr align='center' valign='middle'>
					<td><h5>${deptVO.deptId}</h5></td>
					<td><h5>${deptVO.name}</h5></td>
					<!--
					<td>${deptMap["${deptVO.deptId}"]}</td>
					<td>
					  	<FORM METHOD="post" ACTION="<%=request.getContextPath()%>/dept/dept.do">
					    	<input type="submit" value="э" disabled="true"> 
					    	<input type="hidden" name="deptId" value="${deptVO.deptId}">
					    	<input type="hidden" name="action" value="getOne_For_Update_Dept">
						</FORM>
					</td>
					<td>
					  	<FORM METHOD="post" ACTION="<%=request.getContextPath()%>/dept/dept.do">
						    <input type="submit" value="埃" disabled="true">
						    <input type="hidden" name="deptId" value="${deptVO.deptId}">
						    <input type="hidden" name="action" value="delete_Dept">
						</FORM>
					</td>
					-->
					<!--
					<td>
						<FORM METHOD="post" ACTION="<%=request.getContextPath()%>/dept/dept.do">
							<c:choose>
								<c:when test="${not empty deptMap[deptVO.deptId]}">
								    <input type="submit" class="showDetail fancybox.ajax" value="${deptMap[deptVO.deptId]}"> 
								</c:when>
								<c:otherwise>
								    <input type="submit" class="showDetail fancybox.ajax" value="0"> 
								</c:otherwise>
							</c:choose>
						    <input type="hidden" name="deptId" value="${deptVO.deptId}">
						    <input type="hidden" name="action" value="listEmpsByDeptId_B">
						</FORM>
					</td>
					-->
					<td>
						<h5>
						<c:choose>
							<c:when test="${not empty deptMap[deptVO.deptId]}">
								<a href="<%=request.getContextPath()%>/dept/dept.do?action=listEmpsByDeptId_B&deptId=${deptVO.deptId}">${deptMap[deptVO.deptId]}</a>
							</c:when>
							<c:otherwise>
								0
							</c:otherwise>
						</c:choose>
						</h5>
					</td>
				</tr>
			</c:forEach>
		</table>
		
		<div class="secondary">
			<%if (request.getAttribute("listEmpsByDeptId")!=null) {%>
				<jsp:include page="/dept/listEmpsByDeptId.jsp"/>
			<%} %>
		</div>
	</div> <!-- end of container -->
</div> <!--  end of wrapper -->


</body>
</html>

SCEC/WebContent/dept/listEmpViewByDeptId.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>


<%-- 此頁練習採用 EL 的寫法取值 --%>

<jsp:useBean id="listEmpsByDeptId" scope="request" type="java.util.Set" />
<jsp:useBean id="deptSvc" scope="page" class="com.department.model.DepartmentService" />
<html>
<head>
<title>部門員工 </title>
</head>
<body bgcolor='white'>

<b><font color=red>此頁練習採用 EL 的寫法取值:</font></b>
<table border='1' cellpadding='5' cellspacing='0' width='800'>
	<tr bgcolor='#CCCCFF' align='center' valign='middle' height='20'>
		<td>
		<h3>部門員工 - listEmpsByDeptId.jsp</h3>
		<a href="<%=request.getContextPath()%>/select_page.jsp"><img src="images/back1.gif" width="100" height="32" border="0">回首頁</a>
		</td>
	</tr>
</table>

<%-- 錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font color='red'>請修正以下錯誤:
	<ul>
		<c:forEach var="message" items="${errorMsgs}">
			<li>${message}</li>
		</c:forEach>
	</ul>
	</font>
</c:if>

<table border='1' bordercolor='#CCCCFF' width='800'>
	<tr>
		<th>員工編號</th>
		<th>員工姓名</th>
		<th>職位</th>
		<th>雇用日期</th>
		<th>部門</th>
		<th>修改</th>
		<th>刪除</th>
	</tr>
	
	<c:forEach var="empVO" items="${listEmpsByDeptId}" >
		<tr align='center' valign='middle'>
			<td>${empVO.empId}</td>
			<td>${empVO.name}</td>
			<td>${empVO.onboard}</td>
			<td>
				<c:forEach var="deptVO" items="${deptSvc.all}">
            		<c:if test="${empVO.deptId==deptVO.deptId}">
	            		${deptVO.deptId}【<font color=orange>${deptVO.name}</font> - ${deptVO.name}】
                	</c:if>
                </c:forEach>
			</td>
			<td>
			  <FORM METHOD="post" ACTION="<%=request.getContextPath()%>/emp/emp.do">
			    <input type="submit" value="修改"> 
			    <input type="hidden" name="empId" value="${empVO.empId}">
			    <input type="hidden" name="requestURL"	value="<%=request.getServletPath()%>"><!--送出本網頁的路徑給Controller--><!-- 目前尚未用到  -->
			    <input type="hidden" name="action"	value="getOne_For_Update"></FORM>
			</td>
			<td>
			  <FORM METHOD="post" ACTION="<%=request.getContextPath()%>/emp/emp.do">
			    <input type="submit" value="刪除">
			    <input type="hidden" name="empId" value="${empVO.empId}">
			    <input type="hidden" name="requestURL"	value="<%=request.getServletPath()%>"><!--送出本網頁的路徑給Controller-->
			    <input type="hidden" name="action"value="delete"></FORM>
			</td>
		</tr>
	</c:forEach>
</table>

<br>本網頁的路徑:<br><b>
   <font color=blue>request.getServletPath():</font> <%= request.getServletPath()%><br>
   <font color=blue>request.getRequestURI(): </font> <%= request.getRequestURI()%> </b>
</body>
</html>

SCEC/WebContent/dept/listEmpsByDeptId.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<%
Boolean debugMode = (Boolean)application.getAttribute("debugMode");
Boolean included = (Boolean)request.getAttribute("included");
%>

<%-- 此頁練習採用 EL 的寫法取值 --%>

<jsp:useBean id="listEmpsByDeptId" scope="request" type="java.util.List" />
<jsp:useBean id="deptSvc" scope="page" class="com.department.model.DepartmentService" />
<html>
<head>
<title>部門員工 </title>
<link rel="stylesheet" href="<%=request.getContextPath()%>/util/jquery/tablesorter/style.css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/util/css/common.css" />

<script src="<%=request.getContextPath()%>/util/jquery/jquery-1.9.1.js"> </script>
<script src="<%=request.getContextPath()%>/util/jquery/tablesorter/jquery.tablesorter.js"> </script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script src="<%=request.getContextPath()%>/util/chart/google_chart.js"> </script>
<script type="text/javascript">
	$(function () {
    	$("#empTable").tablesorter({widgets: ['zebra']});
	});
</script>
</head>

<body>

<div class="wrapper">
	<div class="header">
		<% if (included == null) { %>
			<%@include file="../menu.jsp"%>
		<% 
			included = true;
			request.setAttribute("included", included);	
		}
		%>
	</div>

<%-- 錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font color='red'>請修正以下錯誤:
	<ul>
		<c:forEach var="message" items="${errorMsgs}">
			<li>${message}</li>
		</c:forEach>
	</ul>
	</font>
</c:if>

		<table id="empTable" class="tablesorter">
			<thead>
			<tr>
				<th>員工編號</th>
				<th>員工姓名</th>
				<th>部門</th>
				<th>單位</th>
				<th>職位</th>
				<th>職系</th>
				<th>職等</th>
				<th>到職日期</th>
				<th>帳號</th>
				<!--
				<th>修改</th>
				<th>刪除</th>
				-->
			</tr>
			</thead>
			
			<c:forEach var="empVO" items="${listEmpsByDeptId}" >
				<tr align='center' valign='middle'>
					<td>${empVO.empId}</td>
					<td>${empVO.empName}</td>
					<td>${empVO.deptName}</td>
					<td>${empVO.sectionName}</td>
					<td>${empVO.titleName}</td>
					<td>${empVO.seriesName}</td>
					<td>${empVO.levelName}</td>
					<td>${empVO.onboard}</td>
					<td>${empVO.account}</td>
					<!--
					<td>
					  <FORM METHOD="post" ACTION="<%=request.getContextPath()%>/emp/emp.do">
					    <input type="submit" value="修改"> 
					    <input type="hidden" name="empId" value="${empVO.empId}">
					    <input type="hidden" name="requestURL"	value="<%=request.getServletPath()%>">
					    <input type="hidden" name="action"	value="getOne_For_Update"></FORM>
					</td>
					<td>
					  <FORM METHOD="post" ACTION="<%=request.getContextPath()%>/emp/emp.do">
					    <input type="submit" value="刪除">
					    <input type="hidden" name="empId" value="${empVO.empId}">
					    <input type="hidden" name="requestURL"	value="<%=request.getServletPath()%>">
					    <input type="hidden" name="action"value="delete"></FORM>
					</td>
					-->
				</tr>
			</c:forEach>
		</table>

	<c:if test="${debugMode != null}">
		<br>本網頁的路徑:<br><b>
   		<font color=blue>request.getServletPath():</font> <%= request.getServletPath()%><br>
   		<font color=blue>request.getRequestURI(): </font> <%= request.getRequestURI()%> </b>
   	</c:if>
</body>
</html>